### PR TITLE
Add devrel resources

### PR DESCRIPTION
**Pull request by jerdog**
Closing #3 - Test site - https://angry-bartik-f4bcdf.netlify.com/

### CODE REVIEW

**Comment by mary-grace** [comment]
I'm having a hard time with the centered font for the "Why is this group exclusive" section -- can we make that left aligned or two-column (or both)? Otherwise, this looks like a great start! My inclination is to go immediately to Pocket to start pulling more resources, but that can be for another day 😄 Thanks for taking the initiative!

**Comment by jerdog** [comment]
Yeah that's my same feeling. I will make it to column and push live. I'll also start to gather some of my resources to add

**Comment by mbbroberg** [comment]
👏 👏 👏

**Comment by jerdog** [comment]
:sunglasses:

**Pull request merged**
